/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "tweet-card": {
    name: "tweet-card",
    description: "A card that displays a tweet with the author's name, handle, and profile picture.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/vectorui/tweet-card.tsx",
      type: "registry:ui",
      target: "components/vectorui/tweet-card.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/vectorui/tweet-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "marquee": {
    name: "marquee",
    description: "A card that displays a tweet with the author's name, handle, and profile picture.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/vectorui/marquee.tsx",
      type: "registry:ui",
      target: "components/vectorui/marquee.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/vectorui/marquee.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "tweet-card-demo": {
    name: "tweet-card-demo",
    description: "Example showing a tweet card with author info.",
    type: "registry:example",
    registryDependencies: ["https://vectorui.vercel.app/r/tweet-card"],
    files: [{
      path: "registry/example/tweet-card-demo.tsx",
      type: "registry:example",
      target: "components/tweet-card-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tweet-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "tweet-card-images": {
    name: "tweet-card-images",
    description: "Example showing a tweet card with images.",
    type: "registry:example",
    registryDependencies: ["https://vectorui.vercel.app/r/tweet-card"],
    files: [{
      path: "registry/example/tweet-card-images.tsx",
      type: "registry:example",
      target: "components/tweet-card-images.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tweet-card-images.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "tweet-card-meta-preview": {
    name: "tweet-card-meta-preview",
    description: "Example showing a tweet card with meta preview.",
    type: "registry:example",
    registryDependencies: ["https://vectorui.vercel.app/r/tweet-card"],
    files: [{
      path: "registry/example/tweet-card-meta-preview.tsx",
      type: "registry:example",
      target: "components/tweet-card-meta-preview.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/tweet-card-meta-preview.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "marquee-demo": {
    name: "marquee-demo",
    description: "Example showing a tweet card with meta preview.",
    type: "registry:example",
    registryDependencies: ["https://vectorui.vercel.app/r/marquee"],
    files: [{
      path: "registry/example/marquee-demo.tsx",
      type: "registry:example",
      target: "components/marquee-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/marquee-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }